mr3saru/landing

CODE_OF_CONDUCT.md
Close #36
Co-authored-by: Vinicius Zucatti <viniciuszucatti@gmail.com>
=> Create CODE_OF_CONDUCT.md #36

.github/ISSUE_TEMPLATE/custom.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md
Co-authored-by: Vinicius Zucatti <viniciuszucatti@gmail.com>
=> Create Community Standards #36

templates/Home/Industries.tsx
Edited Industries.tsx (sectors) as requested. Only left out the map - it will be added on a different issue.
=> Edit sectors

templates/Home/Welcome.tsx
=> Button to meeting #40

templates/Home/Welcome.tsx
Here's a short video of the code fix working. The site looks great by the way - I'm happy help out with it! 
https://user-images.githubusercontent.com/43625213/156911062-b6f162f9-35c5-4add-9809-f072f1b5fb5b.mov
=> corrected Link component to link to specified URL (fixes issue #64)

components/form/Form.tsx, pages/api/submit-form.ts, pages/api/wakeup-form.ts
Before merge this commit with `main` branch need update env in vercel dashboard
=> Add loading state to submit form

pages/index.tsx
=> Render home page as static HTML #16

components/header/Header.tsx, styles/theme.css, templates/Home/index.tsx
=> Fixed header as user scrolls down and up #37

templates/Home/Welcome.tsx, templates/Home/index.tsx
=> When click on home should scroll to top of the page #45

components/menu/Navbar.tsx, styles/globals.css
=> Fix scroll from nav to sections #44 #46

README.md
This is my first open source first issue. I hope is what you are looking for.
=> Solved Issue: Add ReactJS to README

templates/Home/About.tsx, templates/Home/Contact.tsx, templates/Home/Industries.tsx, templates/Home/Method.tsx, templates/Home/Tech.tsx, templates/Home/Values.tsx
=> Fix anchor position

next.config.js, public/manifest.json
=> Fix PWA settings #47

components/button/Ghost.tsx, components/button/Primary.tsx
Co-authored-by: Tim Losito <tmlosito@192.168.1.5>
=> Add disabled prop to button Ghost and Primary #62

README.md, components/footer/Footer.tsx
=> Add license and release on footer #61

components/form/Form.tsx
=> Disabled form button when request are loading #74

.github/workflows/ci.yml
=> Add CI to workflows

templates/Home/Values.tsx
=> Fix typo #41

package.json, yarn.lock
Update NextJS version
close #55
=> Update Next version #55

.github/workflows/lighthouse-ci.yaml, lighthouserc.js
=> Add Lighthouse CI to Github actions
